export const FETCH_STUDENT_LIST = "FETCH_STUDENT_LIST";
export const FETCH_STUDENT_LIST_SUCCESS = "FETCH_STUDENT_LIST_SUCCESS";
export const FETCH_STUDENT_LIST_FAILED = "FETCH_STUDENT_LIST_FAILED";

export const FETCH_QUESTION_LIST = "FETCH_QUESTION_LIST";
export const FETCH_QUESTION_LIST_SUCCESS = "FETCH_QUESTION_LIST_SUCCESS";
export const FETCH_QUESTION_LIST_FAILED = "FETCH_QUESTION_LIST_FAILED";

export const SUBMIT_REPORT = "SUBMIT_REPORT";
export const SUBMIT_REPORT_SUCCESS = "SUBMIT_REPORT_SUCCESS";
export const SUBMIT_REPORT_FAILED = "SUBMIT_REPORT_FAILED";

export const SUBMIT_REPORT_QUESTIONS = "SUBMIT_REPORT_QUESTIONS";
export const SUBMIT_REPORT_QUESTIONS_SUCCESS = "SUBMIT_REPORT_QUESTIONS_SUCCESS";
export const SUBMIT_REPORT_QUESTIONS_FAILED = "SUBMIT_REPORT_QUESTIONS_FAILED";

export const FETCH_STUDENT_REPORT_LIST = "FETCH_STUDENT_REPORT_LIST";
export const FETCH_STUDENT_REPORT_LIST_SUCCESS = "FETCH_STUDENT_REPORT_LIST_SUCCESS";
export const FETCH_STUDENT_REPORT_LIST_FAILED = "FETCH_STUDENT_REPORT_LIST_FAILED";